### ISSUE TITLE
python train_mars.py --mode=freeze --restore_path=PATH_TO_CHECKPOINT Can anyone tell me what 's the PATH_TO_CHECKPOINT in the upper form ?

### ISSUE THREAD

**Issue by ss199302** [nwojke/cosine_metric_learning#14] opened 2018-08-18 13:26 UTC
@nwojke   python train_mars.py --mode=freeze --restore_path=PATH_TO_CHECKPOINT
Can anyone tell me what the PATH_TO_CHECKPOINT in the upper form is for?

**Comment by nwojke** [comment] 2018-08-20 09:09
It is the path to the trained tensorflow model/checkpoint. E.g., ``python train_mars.py --mode=freeze --restore_path=./output/mars/model.ckpt-100000`` for a checkpoint stored after 100000 iterations, assuming you have used the commands in the README for training.

**Comment by ss199302** [comment] 2018-08-21 01:00
Thank you for your reply, but when I used the finalize derived model for deep_sort, he had the following errors.Thank you for your reply, but when I used the finalize derived ckpt model for deep_sort, he had the following "errors.ValueError: Checkpoint is missing variable [ball/beta]"

**Comment by nwojke** [comment] 2018-08-22 05:53
Then this seems to be a duplicate of #6. I have started looking into it by re-training a model, but didn't get to test the freezed model in deep sort, yet.

**Comment by nwojke** [comment] 2018-08-23 06:41
Closing this because of duplication. Re-open if I am wrong.

**Closed as completed by nwojke** 2018-08-23 06:41 UTC
